/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package so.dang.cool.levee;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;
import static so.dang.cool.levee.MapEntries.*;

import java.util.Map;

class MapEntriesTest {
    @Test void test_onKey() {
        Map.of(
                "apple", "bad",
                "banana", "good",
                "aardvark", "bad"
            ).entrySet()
            .stream()
            .filter(onKey(k -> k.startsWith("b")))
            .forEach(entry -> assertEquals("good", entry.getValue()));
    }

    @Test void test_onValue() {
        Map.of(
                "wrong", 2,
                "perfect", 6,
                "bad", 3,
                "also bad", 8
            ).entrySet()
            .stream()
            .filter(onValue(v -> v == 6))
            .forEach(entry -> assertEquals("perfect", entry.getKey()));
    }


}
